// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcpfwttdttgqrkzzhpri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcGZ3dHRkdHRncXJrenpocHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzEwODQsImV4cCI6MjA3MzA0NzA4NH0.Nxzn6f9gBHpR7XG10RxZbfcBu1RgctuxNBC7kpNJTs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});